name: Build executable for Windows

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-executable:
    runs-on: windows-latest

    env:
      PYTHON_VERSION: 3.11.0

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install pip and numpy
      run: |
        python -m pip install --upgrade pip
        pip install numpy  # Install numpy first

    - name: Install Required Packages
      run: |
        python -m pip install -r requirements.txt || true  # First attempt
        # Attempt to install pygraphviz with Graphviz paths if the first attempt fails
        python -m python -m pip install --config-settings="--global-option=build_ext" `
              --config-settings="--global-option=-IC:\Program Files\Graphviz\include" `
              --config-settings="--global-option=-LC:\Program Files\Graphviz\lib" `
              pygraphviz

    - name: Create ChemProp2.bat file
      run: |
        echo '@echo off' > ChemProp2.bat
        echo 'python -m streamlit run Home.py' >> ChemProp2.bat

    - name: Create All-in-one executable folder
      run: |
        mkdir streamlit_exe
        mv ChemProp2.bat streamlit_exe
        cp -r src streamlit_exe
        cp -r pages streamlit_exe
        cp -r assets streamlit_exe
        cp -r example-data streamlit_exe
        cp -r .streamlit streamlit_exe
        cp Home.py streamlit_exe

    - name: Compress streamlit_exe folder to ChemProp2.zip
      run: |
        7z a ChemProp2.zip ./streamlit_exe/* -r

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ChemProp2
        path: ChemProp2.zip
