name: Build executable for Linux

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-executable:
    runs-on: ubuntu-latest

    env:
      PYTHON_VERSION: 3.11.0 

    steps:
    - name: Checkout the code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Build executable with PyInstaller
      run: |
        pyinstaller --onefile --name ChemProp2 run.py 

    - name: Archive executable
      uses: actions/upload-artifact@v4
      with:
        name: Linux-Executable
        path: dist/ChemProp2  # Path to the generated executable
