name: Build executable for Windows

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-executable:
    runs-on: windows-latest

    env:
      PYTHON_VERSION: 3.11.0

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        activate-environment: chemprop-env
        auto-update-conda: true
        channels: conda-forge  

    - name: Install pygraphviz and other dependencies
      run: |
        conda install -y -c conda-forge pygraphviz
        conda activate chemprop-env && pip install -r requirements.txt

    - name: Create ChemProp2.bat file
      run: |
        echo '@echo off' > ChemProp2.bat
        echo 'CALL "C:\Miniconda3\condabin\conda.bat" activate chemprop-env' >> ChemProp2.bat
        echo 'python -m streamlit run Home.py' >> ChemProp2.bat

    - name: Create All-in-one executable folder
      run: |
        mkdir streamlit_exe
        mv ChemProp2.bat streamlit_exe
        cp -r src streamlit_exe
        cp -r pages streamlit_exe
        cp -r assets streamlit_exe
        cp -r example-data streamlit_exe
        cp -r .streamlit streamlit_exe
        cp Home.py streamlit_exe

    - name: Compress streamlit_exe folder to ChemProp2.zip
      run: |
        7z a ChemProp2.zip ./streamlit_exe/* -r

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ChemProp2
        path: ChemProp2.zip